export const ActionTypes ={
    FETCH_SUCCESS : "FETCH_SUCCESS",
    CHANGE_VALUE_INPUT: "CHANGE_VALUE_INPUT",
    CHANGE_VALUE_CHECKBOX: "CHANGE_VALUE_CHECKBOX",
    CHANGE_DATE: "CHANGE_DATE",
    BORROW_A_BOOK:"BORROW_A_BOOK",
    RETURN_A_BOOK:"RETURN_A_BOOK",
    CONFIRM_RETURNED_BOOK:"CONFIRM_RETURNED_BOOK",
    SHOW_MODAL: "SHOW_MODAL"
}